### ISSUE TITLE
Minimize

### ISSUE THREAD

**Issue by Saph1s** [kkevinm/iTunes-Discord-RP#25]
When minimizing a program, it remains on the panel with open programs and in the tray. When you click the tray icon, the application disappears / appears on the panel with open programs. Usually, it should be when I click "minimize" the application is removed in the tray, and does not remain on the panel.

**Comment by kevinmussi** [comment]
I don't really know if I can do anything about that, the icons showing up in the panel and in the system tray is handled by the operative system (I think?), so I don't think I can change it within Java (I'm pretty sure the fact that it disappear from the opened program bar when hitting the tray icon is a consequence of the app not having any visible windows, since I didn't do anything about that in the code).

**Comment by wynterthecat** [comment]
A similar issue on macOS, I would like to hide the app icon from the Dock as it takes up space and there's not really anything useful for it to be doing there. I can Command-H to hide it without leaving its minimized window in the Dock next to the Trash, but I can't hide the actual application logo. I know some apps on macOS can hide their icon from the Dock, I don't know how though and I don't know if Java doesn't let you do that. It would be a good feature to implement, though.

**Comment by kevinmussi** [comment]
I tried doing that but it didn't work quite right. The JVM has an option to remove the dock icon but then the app wouldn't respond, so I just didn't bother with it (on Windows, the app is hidden from the dock automatically by the OS so it's not an issue there).

**Comment by wynterthecat** [comment]
Understandable. It is a bit of an annoyance that it takes up space but oh well, not the end of the world. I suppose if it becomes possible in the future, great; if not, it still does its job.
