### ISSUE TITLE
Make red exit button on app minimize not close

### ISSUE THREAD

**Issue by Kentakoong** [kkevinm/iTunes-Discord-RP#32]
![2182F458-AB03-416F-82D8-00A491C320AC](https://user-images.githubusercontent.com/35761701/89710204-07b29300-d9ab-11ea-8b42-042633d5646a.png)

**Comment by kkevinm** [comment]
Why? There's the orange button to minimize.

**Comment by Kentakoong** [comment]
uhhh sometimes I accidentally clicked on it and it just quits
Annoying for me

**Comment by Kentakoong** [comment]
coz macos have the right click and click quit option

**Comment by Kentakoong** [comment]
just an idea for me

**Comment by Kentakoong** [comment]
one thing though, I want this to be fixed, I guess
![4A607357-5B69-464C-81AC-72022C1F1A68](https://user-images.githubusercontent.com/35761701/89713414-c2e62680-d9c1-11ea-9850-7938c1c39d24.png)
the elapsed thing I don't know if this is a bug or not but when I repeated a song it won't redo to 00:00 like the Apple Music app does

**Comment by kkevinm** [comment]
Well, I won't change that. I can look in the time elapsed issue, though.

**Comment by Kentakoong** [comment]
okay thanks for the response though.

**Comment by kkevinm** [comment]
The issue with the elapsed time should be fixed now in v1.5.5!

**Comment by wynterthecat** [comment]
As another Mac user the fact that the red button quits the app does really bother me too. The yellow button makes it take up space on the Dock. 

OS X (and now macOS) is a document-based OS, not an application based OS. In Windows, closing a window is tied to closing the whole app, assuming there's not another window of the same app open. But, in macOS, with some (slightly bothersome at times) exceptions, closing a window JUST affects the document within it, not the application. As an artist and writer, this behavior fits better with how I sort of understand the "things" in my computer. As such, I habitually hit the red button to close just the window of an application when I don't need it, and hit Command-Q when I actually want to quit the application. I have to go out of my way to hit Command-H to hide the window instead of quit the application, which is passable but not ideal.

Of course, we're at your mercy and the fact that someone made this program for us Apple Music and iTunes users in general is generous, but if it's not stupidly difficult it would be nice if the red button was modified to match the typical behavior for a Mac. For example, red button on the Music app will keep Music running but close the window.

**Comment by kkevinm** [comment]
Mh well, that makes sense. Making the window hide rather than closing the app is easy, but there's an issue: to show the window again you have to use the menu bar icon, because hitting the Dock icon won't make it show again.

**Comment by wynterthecat** [comment]
Do you mean you couldn't re-show the app by searching for it in Spotlight or Launchpad? (If you're unsure, I can test it for you.) Either way, the menubar icon is fine as it takes up less space and it's in a fixed location. On that note, it would be nice if an option to make it either flat white or flat black (for Dark Mode and Light Mode respectively) so that it blends in with system icons a little better.
<img width="851" alt="Screen Shot 2020-08-08 at 3 38 15 PM" src="https://user-images.githubusercontent.com/66891620/89719371-2efa6780-d98d-11ea-8b3d-2c5c5505dc3f.png">

**Comment by kkevinm** [comment]
Yes, I think as long as the app is open, but hidden when hitting the red button, it can be shown again only by using the menu bar icon. I'm unsure if this would be better than having the app close, since you can already hide the app with either CMD-H or the menu bar icon.
Speaking of that, I'll look into adding an option for that.

**Comment by wynterthecat** [comment]
I think either way it is better for the red button to just hide, since the menu bar icon can bring it back. It's less of a hassle to accidentally hide it than to accidentally close it and need to start it back up and reconnect. Perhaps a preferences option if nothing else to allow one to choose their behavior, though I think most people would expect the hide behavior. 

And I'd like to just mention that it's pretty nice you are actually considering what I'm saying even after the ticket was closed. Many developers I have dealt with just decide to do what they will do. So cheers

**Comment by wynterthecat** [comment]
I did check, and it's not possible to accidentally dismount the icon from the menu bar, too. And the app does show in the Force Quit menu. So if it does get hidden and there is no way to bring it back, which is unlikely seeing as its icon will always show in the menu bar, it can be force quit and relaunched. Worst case scenario.

**Comment by kkevinm** [comment]
Yeah, I guess my doubt is that it's counterintuitive to how it usually works on Mac: when you hide the window with the red button, hitting the app's icon in the Dock (for example) will show the window again. Since it's not what happens here, it could be seen as weird that you cannot do anything with the Dock icon, and you have to use the menu bar icon.

**Comment by wynterthecat** [comment]
Yeah I guess it is a little odd. Still, in most cases it's a launch once and leave it type thing, and just being able to see that it's started up on login and then click the red dot is the most effective. I imagine this odd behavior in general is subject to the JRE?

**Comment by kkevinm** [comment]
Yeah, I haven't found a way to add a listener or something when the app is "opened" again. But anyway, I edited the v1.5.5 files to include the new behavior.

**Comment by wynterthecat** [comment]
Awesome, I'll update to the newest files. And yeah, there's always gotta be that one thing where it's like "but why? isn't this a super basic common thing?" lmao

**Comment by wynterthecat** [comment]
The hide/show behavior is now working as expected, thanks!
